### ISSUE TITLE
File bugs for new actionable crashes on Nightly

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#1944]
We should investigate leveraging [crash-clouseau ](https://github.com/mozilla/crash-clouseau) to identify new actionable crashes.
```[tasklist]
### Tasks
- [ ] https://github.com/mozilla/crash-clouseau/pull/23
- [ ] https://github.com/mozilla/libmozdata/pull/232
- [ ] https://github.com/mozilla/libmozdata/pull/235
- [ ] https://github.com/mozilla/libmozdata/pull/238
- [ ] https://github.com/mozilla/bugbot/pull/2117
```
