### ISSUE TITLE
Rename the bot to BugBot

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#1978]
```[tasklist]
### Tasks
- [x] Announce the survey results on #ee
- [x] Rename the repo on GitHub to `bugbot`
- [ ] https://github.com/mozilla/bugbot/issues/2013
- [x] Rename the bot's account on Bugzilla
- [x] Rename the bot's service account on GCP
- [x] Update the wiki page
- [x] Update the wiki page template to point to the new repo address
- [ ] https://github.com/mozilla/bugbot/issues/2015
- [ ] https://github.com/mozilla/bugbot/issues/2016
- [ ] https://github.com/mozilla/bugbot/issues/2017
- [ ] https://github.com/mozilla/bugbot/issues/2018
- [x] Rename the Slack channel
```

**Comment by suhaibmujahid** [comment]
Done! Tank you, @calixteman and @marco-c, for updating the name on Bugzilla.
