### ISSUE TITLE
Improve the directory structure

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#1989]
```[tasklist]
### Tasks
- [x] Rename the `scripts` directory to `tools`
- [x] Move the `tests` directory to the root
- [x] Move the `configs` directory to the root
- [x] Move the cron scripts and other scripts into a new directory called `scripts`
```
