### ISSUE TITLE
Fill the regression related metadata when filing a crash bug with known regressor

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#2144]
```[tasklist]
### Tasks
- [ ] https://github.com/mozilla/bugbot/issues/2153
- [ ] https://github.com/mozilla/bugbot/issues/2152
- [ ] https://github.com/mozilla/bugbot/issues/2162
- [ ] https://github.com/mozilla/bugbot/issues/2163
```

**Comment by marco-c** [comment]
When we know the regressor, we can fill all status flags (also those for beta, release, esr)
